# Generated by Django 4.2.30 on 2026-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('pastas', 'Pastas'), ('carnes', 'Carnes'), ('pescados', 'Pescados'), ('bebidas', 'Bebidas'), ('postres', 'Postres'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Opcional. Si se deja vacía, el menú muestra un placeholder.', null=True, verbose_name='URL de imagen'),
        ),
    ]
